# Disable the local .yarn/cache folder
enableGlobalCache: false

# Prevent automatic installation of missing dependencies
enableImmutableInstalls: true

# Ignore scripts in packages unless you explicitly allow them
enableScripts: true

# Reduce metadata for smaller installs (optional)
compressionLevel: 0

# Default nodeLinker is 'pnp', use 'node-modules' for compatibility
nodeLinker: node-modules